Draft: Add base starting insertion point when no chunk ID is provided (MSC2716)
matrix-org/synapse pull request #10250
Opened 2021-06-25 06:12 UTC by MadLittleMods

Add base starting insertion point when no chunk ID is provided

This is so we can have the marker event point to this initial
insertion event and be able to traverse the events in the first chunk.

Before | After
--- | ---
![](https://user-images.githubusercontent.com/558581/123378326-35b4ad80-d552-11eb-98d6-e4cd4053f1f8.png) | ![](https://user-images.githubusercontent.com/558581/123378439-61d02e80-d552-11eb-8499-e0cc05b91e91.png)

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

2021-06-25 06:16 UTC, MadLittleMods commented on synapse/rest/client/v1/room.py
> +            pass
We need a database index to make this lookup fast. Going to add this in https://github.com/matrix-org/synapse/pull/10245

2021-06-25 06:27 UTC, MadLittleMods commented on synapse/rest/client/v1/room.py
> +            ]
Here is where we are creating the base insertion event

2021-07-07 12:31 UTC, erikjohnston commented
I'm a little bit confused. Shouldn't the marker event be pointing at the next chunk? The same way that the insertion events are pointing at the next chunk?

2021-07-07 15:32 UTC, erikjohnston commented
> I'm a little bit confused. Shouldn't the marker event be pointing at the next chunk? The same way that the insertion events are pointing at the next chunk?

So the way to think about this is that the base insertion event isn't in the first chunk per se, as ideally it would be part of the original DAG when we first created the room. However, we want to support adding historical events even where we don't have insertion events, and so we create a new base insertion event in an ad hoc manner.

2021-07-07 15:40 UTC, MadLittleMods commented
> So the way to think about this is that the base insertion event isn't in the first chunk per se, as ideally it would be part of the original DAG when we first created the room. However, we want to support adding historical events even where we don't have insertion events, and so we create a new base insertion event in an ad hoc manner.

It would probably be more accurate if showed the chunk connection from the base insertion point. I can't make the graph align better but here is how it would look like. The insertion point is part of the first chunk currently which made it easy to insert and add.

![](https://user-images.githubusercontent.com/558581/124788863-6233d680-df0f-11eb-90fa-b02b78a27737.png)


Perhaps it should float more as you're thinking about:

![](https://user-images.githubusercontent.com/558581/124789194-ac1cbc80-df0f-11eb-8b0c-fb598e64e9f8.png)

2021-07-07 15:41 UTC, erikjohnston requested changes
I think this all makes sense

2021-07-07 15:41 UTC, erikjohnston commented on synapse/rest/client/v1/room.py
> +        # to as a starting point.
```suggestion
        # We don't always have an insertion event to hang more history off of
        # (ideally they'd be one in the main DAG, but that's not the case if
        # we're wanting to add history to e.g. existing rooms without such an
        # event), in which case we just create a new insertion event that will
        # then get pointed to by a "marker" event.
```

Or something to that effect, I'm terrible with words.

2021-07-07 15:41 UTC, erikjohnston commented on synapse/rest/client/v1/room.py
> +            Tuple of event ID and stream ordering position
```suggestion
        """Creates an event dict for an "insertion" event with the proper fields
        and a random chunk ID.
        
        Args:
            sender: The event author MXID
            origin_server_ts: Timestamp when the event was sent
            
        Returns:
            Tuple of event ID and stream ordering position
```

2021-07-07 15:41 UTC, erikjohnston commented on synapse/rest/client/v1/room.py
> +        next_chunk_id = random_string(64)
```suggestion
        next_chunk_id = random_string(8)
```

These will be scoped per room, so eight characters feels like more than enough? Which I think is equivalent to a ~50bit integer. 64 characters just seems needlessly long.

2021-07-08 04:46 UTC, MadLittleMods commented on synapse/rest/client/v1/room.py
> +            )
@erikjohnston I've decided to make the base insertion event float off on its own so its easier to reason about in my head

![](https://user-images.githubusercontent.com/558581/124863797-61398e00-df7d-11eb-8d28-6463a4ce0706.png)

2021-07-08 10:38 UTC, erikjohnston approved these changes

2021-07-09 01:25 UTC, merged

2021-07-09 01:27 UTC, MadLittleMods commented
@erikjohnston Thanks for the review on this one! Really valuable to talk through it to see how we align 🦃