doc:Add beta configuration for Authelia as OIDC provider.
matrix-org/synapse pull request #10374
Opened 2021-07-12 14:33 UTC by henniaufmrenni

This PR adds a configuration example to configure Authelia as an OIDC provider.  I've asked on #synapse-dev:matrix.org whether I should wait with this because, this is currently an Authelia beta feature, but I was told that it would be okay to open it right now. However if this should not be the case, I can of course revert this back to a draft and reopen it whenever the Authelia OIDC implementation hits GA.

Signed-off-by: Hendrik Stöldt<65598400+henniaufmrenni@users.noreply.github.com>

### Pull Request Checklist

* [x ] Pull request is based on the develop branch
* [ x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [ x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

2021-07-27 16:56 UTC, clokep requested changes

2021-07-27 16:56 UTC, clokep commented on docs/openid.md
> +3. Add the following section to the Authelia configuration.yaml.
I'm not sure if it makes sense to include a full configuration in here. Maybe we can point to some docs from Authelia instead and note what to change?

2021-07-27 16:56 UTC, clokep commented on docs/openid.md
> +[Authelia][authelia] is an open-source authentication and authorization server. Authelia supports the OIDC OP role currently in beta - you can follow the progress [here](https://www.authelia.com/docs
Please wrap all your text about ~80 characters.

2021-07-27 16:56 UTC, clokep commented on docs/openid.md
> +    issuer: "https://[authelia public baseurl]
```suggestion
    issuer: "https://[authelia public baseurl]"
```

2021-07-27 16:56 UTC, clokep commented on docs/openid.md
> +    jwks_uri: "https://[authelia public baseurl]/api/oidc/jwks"
The documentation seems to suggest that provider discovery is supported, which is more future proof than hard-coding each of these.

I think Synapse uses it automatically unless you set `discover` to `False`, maybe try removing these and seeing if it still works?

2021-08-18 10:30 UTC, anoadragon453 commented
Hey @henniaufmrenni, are you able to continue working on this? :slightly_smiling_face:

2021-09-09 13:57 UTC, anoadragon453 commented
I'm going to close this PR as it appears to be stale. You're more than welcome to re-open if you'd like to work on it again. :slightly_smiling_face:

2021-09-09 13:57 UTC, closed without merging