Make oEmbed globs configurable and extract more info from the response
matrix-org/synapse pull request #10392
Opened 2021-07-14 10:56 UTC by t3chguy

Fixes https://github.com/matrix-org/synapse/issues/9733

Needs moar tests, some refactoring to tidy up the code, to load the providers.json from upstream automagically

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

2021-07-28 09:00 UTC, richvdh commented
A thought occurs to me (sorry for moving the goalposts): rather than embedding a list of oEmbed provider URLs, could we instead pull the `<link rel="alternate" type="application/json+oembed">` value from the response?

Youtube's `watch` links include content such as the following:

```
<link rel="alternate" type="application/json+oembed" href="https://www.youtube.com/oembed?format=json&amp;url=https%3A%2F%2Fwww.youtube.com%2Fwatch%3Fv%3DRzJf02TIqxk" title="PURE RELAXATION - SERVER SOUNDS by Hetzner">
```

https://oembed.com/#section7 says:

> There are currently 290 providers in the registry. Providers and consumers are strongly encouraged to use the discovery mechanism, rather than the registry.


... of course that doesn't work for Twitter, so maybe we need to support a static list as well. Gah.

2021-07-28 10:57 UTC, ajs124 commented
Instead of maintaining our own static list, why can't we just pull in the registry from https://oembed.com/providers.json?

2021-07-28 11:07 UTC, clokep commented
> Instead of maintaining our own static list, why can't we just pull in the registry from [oembed.com/providers.json](https://oembed.com/providers.json)?

I had recommended this to @t3chguy as a follow-up to keep this PR smaller. It is a bit unclear though if we need to support custom / configurable values. I can come up with use-cases for it, but I'm unsure if they're realistic or not.

2021-08-06 14:16 UTC, richvdh requested changes
I've written some words about how I think we should approach this over at https://github.com/matrix-org/synapse/issues/2752#issuecomment-894273747. TL;DR: let's use a `providers.json` file rather than config.

Also: please could you separate the bits of this PR that aren't to do with updating the glob list out to a separate PR?

2021-08-31 22:39 UTC, clokep commented
Hello! The main gist of this PR was implemented by #10714. I think the "extra more info" bits could be moved to a separate PR, but will likely be difficult to rebase on the changes.

2021-09-13 18:56 UTC, clokep commented
I'm going to close this in-lieu of #10814, which I *think* makes the same improvements.

2021-09-13 18:56 UTC, closed without merging