Allow /createRoom to be run on workers
matrix-org/synapse pull request #10564
Opened 2021-08-09 23:25 UTC by anoadragon453

Fixes https://github.com/matrix-org/synapse/issues/7867

As stated in the issue, `/createRoom` could only be run on the main process due to the `public_room_list_stream` only being writable by the main process. It turns out however that this stream was unused - meaning that we could simply rip it out. This unblocked moving `/createRoom` off the main process :tada: (It potentially also unblocks moving the Delete Room Admin API - but that's the subject of another PR).

This PR (will be) based on #XXXX which removes `public_room_list_stream` (just reading/writing to the table - not the table itself, for now). This PR does the job of mounting the endpoint to workers and moving the database method `store_room` to the `RoomWorkerStore`.

2021-08-09 23:36 UTC, anoadragon453 commented on synapse/replication/slave/storage/room.py
>          return super().process_replication_rows(stream_name, instance_name, token, rows)
I'm unsure whether this method can be removed entirely now.

2021-08-10 09:42 UTC, erikjohnston requested changes
Can you update `docs/workers.md` please?

2021-08-10 09:42 UTC, erikjohnston commented on changelog.d/10564.feature
> +Allow creating a room to be handled by worker processes.
```suggestion
Add support for routing `/createRoom` to workers.
```

2021-08-10 12:55 UTC, anoadragon453 commented on synapse/replication/slave/storage/room.py
>          return super().process_replication_rows(stream_name, instance_name, token, rows)
Removed in #10565.

2021-08-13 10:00 UTC, erikjohnston approved these changes
Once the other PR has landed

2021-08-17 13:33 UTC, merged