Ask consent on SSO registration with default mxid
matrix-org/synapse pull request #10733
Opened 2021-09-01 07:28 UTC by AndrewFerr

Fixes #10732

Signed-off-by: Andrew Ferrazzutti <fair@miscworks.net>

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

2021-09-01 15:55 UTC, richvdh requested changes
Hi, thanks for the contribution!

> Note that I wasn't able to get the SyTest integration tests working, though unit tests & manual checks passed.

They run as part of our CI, so you're fine there.

> Regarding the change itself, a different approach than the one I used may be desired, as all I did was hack at a `UsernameMappingSession` to make it think that the user chose a username already, when it was really the mapping provider that did. This seems to do exactly what it needs to do, yet it still feels icky.

I sortof see what you mean, though I think broadly it is a sensible approach, if we consider it more as just going through the steps of the flow that are required. I think we might want to modify the implementation a bit though.

In particular, I'd suggest that we have a method which inspects an active `UsernameMappingSession` and redirects to the appropriate page for the next step. For example, if we don't yet have a `chosen_localpart`, we redirect to the username picker. If we have a `chosen_localpart` but need to gather consent, we redirect to the `new_user_consent` page. If we've got everything, we redirect to `/sso_register`. 

We could then call that method from `complete_sso_login_request`, `handle_submit_username_request` and `handle_terms_accepted`, which would reduce the amount of duplicated code.

Let me know what you think.

2021-09-01 15:55 UTC, richvdh commented on changelog.d/10733.bugfix
> +Allow user registration via SSO to require consent tracking for SSO mapping providers that don't prompt for Matrix ID selection.
Feel free to add yourself here:

```suggestion
Allow user registration via SSO to require consent tracking for SSO mapping providers that don't prompt for Matrix ID selection. Contributed by @AndrewFerr.
```

2021-09-01 22:42 UTC, AndrewFerr commented
> I sortof see what you mean, though I think broadly it is a sensible approach, if we consider it more as just going through the steps of the flow that are required. I think we might want to modify the implementation a bit though.
> 
> In particular, I'd suggest that we have a method which inspects an active `UsernameMappingSession` and redirects to the appropriate page for the next step. For example, if we don't yet have a `chosen_localpart`, we redirect to the username picker. If we have a `chosen_localpart` but need to gather consent, we redirect to the `new_user_consent` page. If we've got everything, we redirect to `/sso_register`.
> 
> We could then call that method from `complete_sso_login_request`, `handle_submit_username_request` and `handle_terms_accepted`, which would reduce the amount of duplicated code.
> 
> Let me know what you think.

That sounds reasonable; thanks for the feedback. I can get something ready for it.

2021-09-09 07:50 UTC, AndrewFerr commented
Okay--this should be ready now.

2021-09-10 09:35 UTC, richvdh approved these changes
looks great. Thank you so much!

2021-09-10 09:36 UTC, merged