Fix event context for outliers in important MSC2716 spot
matrix-org/synapse pull request #10938
Opened 2021-09-29 03:06 UTC by MadLittleMods

Fix event context for outlier causing failures in all of the MSC2716 Complement tests.

The `EventContext.for_outlier` refactor happened in https://github.com/matrix-org/synapse/pull/10883 and this spot was left out.

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

2021-09-29 11:26 UTC, richvdh requested changes
Sorry for missing this one, @MadLittleMods. I didn't realise we had code in the MessageHandler which generated outliers :/

2021-09-29 11:26 UTC, richvdh commented on synapse/handlers/message.py
> +        context = await self.state.compute_event_context(event)
computing event context isn't free (eg, it creates state groups in the database). We shouldn't do it if we're about to throw it away.

2021-09-29 11:26 UTC, richvdh commented on synapse/handlers/message.py
>              event.internal_metadata.outlier = builder.internal_metadata.outlier
```suggestion
            event.internal_metadata.outlier = True
```

2021-09-29 11:26 UTC, richvdh commented on changelog.d/10938.bugfix
> +Fix [MSC2716](https://github.com/matrix-org/matrix-doc/pull/2716) `/batch_send` endpoint not being able to create outlier events.
we should say which version the bug was introduced in:

```suggestion
Fix bug introduced in Synapse 1.44 which caused the experimental [MSC2716](https://github.com/matrix-org/matrix-doc/pull/2716) `/batch_send` endpoint to return a 500 error.
```

(can we be more specific? "create outlier events" is too opaque for an admin - what causes it to generate outliers?)

2021-09-29 17:13 UTC, MadLittleMods commented
Thanks for the review pass @richvdh! It's hard to see when the MSC2716 tests don't run in CI yet 🙂

2021-09-30 09:55 UTC, richvdh approved these changes
thanks!

2021-09-30 10:37 UTC, reivilibre commented
Merged #10938 into release-v1.44.

2021-09-30 10:37 UTC, closed without merging

2021-09-30 16:49 UTC, MadLittleMods commented
Thanks for the review @richvdh and for the merge @reivilibre 🦜