Move sql file for `remove_deleted_devices_from_device_inbox` into v65
matrix-org/synapse pull request #11303
Opened 2021-11-11 08:57 UTC by dklimpel

Between creation and merging PR #10969 was an schema update in #10975 (v1.46.0). That is the reason why the bg task remove_deleted_devices_from_device_inbox is not running in v1.47.0.rc2. https://github.com/matrix-org/synapse/pull/10969/files#diff-d664ca027d1e3730574905917ca3ab47ab476edca1434fe0ae08b8bce06d1fdb has to move from schema 64 to 65.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2021-11-11 14:04 UTC, anoadragon453 requested changes
lgtm otherwise! Thanks for catching this.

2021-11-11 14:52 UTC, anoadragon453 approved these changes

2021-11-11 15:01 UTC, merged

2021-11-11 15:01 UTC, erikjohnston commented
Do we need to worry about this being re-inserted when the old background update is still in the table?

2021-11-11 15:35 UTC, dklimpel commented
I think: No. At second run there is no result. The job removes old entries in the database.

2021-11-11 15:54 UTC, erikjohnston commented
I was more thinking of the case of us trying to `INSERT` into the `background_updates` an update that is already there, sine I think there is a unique constraint?

2021-11-11 16:29 UTC, dklimpel commented
This PR changed the ordering number. In worst case there a running two jobs parallel and creates more load at DB.

2021-11-12 18:18 UTC, dklimpel commented
Should the PR also come in version 1.47.0?

2021-11-15 11:47 UTC, anoadragon453 commented
@dklimpel Indeed. We'll make a v1.47.0rc3 with it included.