Push notifications for invites
matrix-org/synapse pull request #11410
Opened 2021-11-22 22:52 UTC by Bubu

Based on #11409

Closes #8626

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2021-11-30 16:50 UTC, reivilibre requested changes
Would you be happy to merge in (or rebase, at your preference, since nothing has been reviewed yet) develop? I gave it a quick try but there were cases where the better push typing PR seems to have diverged, so I don't trust myself to do it properly.

2021-11-30 18:37 UTC, Bubu commented
@reivilibre Rebased on develop! Thanks for looking at it :).

2021-12-01 12:08 UTC, reivilibre reviewed
Thanks for doing the rebase!

I've been staring at this for a while — I suspect it's not 'right' architecturally but I really wanted to say something helpful.

The main red flag I see with it is that push notifications are sent by a specific worker ([the `pusher` worker type](https://matrix-org.github.io/synapse/latest/workers.html#synapseapppusher)) but in this PR, a worker handling federation will be sending the push.

I'll have to be honest with you that I'm not very familiar with the structure of the push code here and what I do know is from a few years ago..

My suspicion is that maybe we should be putting actions into the staging area, *then* persisting the event, with a *catch* clause that will back out the staging area if the persist fails. (That said, I just described the same thing that `_run_push_actions_and_persist_event` does.)

Maybe the answer is that `_run_push_actions_and_persist_event` needs to be adapted to be happy with outliers (at least for invite events) and then the invite code should use that instead of plain `persist_events_and_notify`?

I just worry that I don't know *why* outliers aren't allowed in `_run_push_actions_and_persist_event` and that's probably pretty critical for doing this. It might be that we need to carry some special cases down for these outlier invites.

I'll put this back on the queue in case anyone else has any more intelligent thoughts.

2021-12-10 13:24 UTC, squahtx commented
I tried to review and ended up coming to roughly the same conclusion as @reivilibre above. The change doesn't sit right architecturally, but I'm not familiar enough with this part of the code to suggest what should be done instead.

Additionally, won't this send notifications twice for invites into rooms that the homeserver is already participating in?
#8626 seems to suggest that notifications are already sent for such rooms.

2021-12-16 18:02 UTC, richvdh requested changes
As others have said, this crosses various architecture boundaries.

What happens if we simply relax the `assert not event.internal_metadata.outlier` in `_run_push_actions_and_persist_event` to allow events with `event.internal_metadata.out_of_band_membership`, and call that instead of `persist_events_and_notify`?

2022-08-22 13:46 UTC, anoadragon453 commented
This PR has been sitting around for a while. I'm going to close it for now to tidy the review queue a bit, but please re-open it (and rebase on latest `develop`) if you'd like to keep working on it!

2022-08-22 13:46 UTC, closed without merging