Improve docker docs
matrix-org/synapse pull request #11640
Opened 2021-12-23 16:10 UTC by chmac

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [ ] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Couple of tweaks to documentation. Doesn't include all the above methods, assuming they don't all apply to docs.

Partly this came from #8304.

2022-01-04 18:58 UTC, DMRobertson reviewed
Thanks for this! For CI to pass, I think we just need a newsfile entry (`11640.doc`) which describes the change.

(Given that we don't recommend sqlite for production, I wonder if we ought to make the official docker images default to using postgres? cc @matrix-org/synapse-core )

2022-01-04 18:58 UTC, DMRobertson commented on contrib/docker/docker-compose.yml
> +    # NOTE: You must edit the config file to use postgres, it defaults to sqlite
```suggestion
    # NOTE: You must edit homeserver.yaml to use postgres, it defaults to sqlite
```

2022-01-04 18:58 UTC, DMRobertson requested changes
as above, newsfile please!

2022-01-04 20:11 UTC, chmac commented
@DMRobertson Switching the default on docker would make a lot of sense.

I'm not sure what a news file is or how to add one. Also, I won't make any more changes to the PR. I'm happy for somebody else to do whatever steps are required or abandon it altogether, I have no attachment to it getting merged. I thought it might make an improvement to the docs, but I leave that up to others to decide.

Happy to close this if it requires work to get merged.

2022-01-05 10:20 UTC, reivilibre commented on docker/README.md
> +By default the config will use sqlite. See the [docs on using postgres](https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md) for more info on how to use postgres. Until this section i
```suggestion
By default the config will use SQLite. See the [docs on using Postgres](https://github.com/matrix-org/synapse/blob/develop/docs/postgres.md) for more info on how to use Postgres. Until this section is improved [this issue](https://github.com/matrix-org/synapse/issues/8304) may provide useful information.
```

2022-01-05 10:50 UTC, merged