HAProxy guide update based on #12124
matrix-org/synapse pull request #12279
Opened 2022-03-23 20:24 UTC by villepeh

This PR includes HAProxy reverse proxy guide update. HAProxy will still listen to IPv4 and IPv6 ports but doesn't send IPv4-mapped address to homserver anymore. Also moved forwarding headers to the **backend** part as recommended by several guides.

PR also includes a simple delegation guide.

Signed-off-by: Villepeh

2022-03-23 20:27 UTC, villepeh commented
#12124

2022-03-24 13:50 UTC, villepeh commented
Changelog filename mess up fixed.

2022-03-24 21:18 UTC, H-Shay commented
Looks like the CI has gone wonky-maybe rerun the GHA workflows?

2022-03-24 21:25 UTC, villepeh commented
> Looks like the CI has gone wonky-maybe rerun the GHA workflows?

@clokep fixed something that allowed me to merge with the develop branch. Hopefully the PR is fine now.

2022-03-25 12:48 UTC, richvdh requested changes
thanks for this! I've got a few questions and comments though.

2022-03-25 12:48 UTC, richvdh commented on docs/reverse_proxy.md
> +  option forwardfor
unfortunately this is not secure, due to https://github.com/matrix-org/synapse/issues/9471 (for which fixes are welcome!) - `option forwardfor` makes haproxy *append* an entry to any existing `X-Forwarded-For` header, whereas synapse uses the *first* entry in the header.

2022-03-25 12:48 UTC, richvdh commented on docs/reverse_proxy.md
> +  http-request return status 200 content-type application/json lf-string '{"m.server": {"base_url": "matrix.example.com:443"}}' if { path -i -m str /.well-known/matrix/client }
this is not a valid `/.well-known/matrix/client` file.

Also: don't you need to set CORS headers for a client .well-known go work?

2022-03-25 12:48 UTC, richvdh commented on docs/reverse_proxy.md
> +  server matrix localhost:8008 # 127.0.0.1:8008 or [::1]:8008 should also work
this isn't very clear. Why are we giving multiple options here? Which is the user supposed to do? (What was wrong with the original?)

2022-03-25 12:48 UTC, richvdh commented on docs/reverse_proxy.md
> +  # Uncomment the line in the end to disable TLS <= v1.2
again, I don't think this is the place to be giving the user lots of different options. Let's make a single recommendation. If advanced users want to do things like restrict TLS versions they can research how to do it themselves.

2022-03-25 12:48 UTC, richvdh commented on docs/reverse_proxy.md
> -  bind :::443 v4v6 ssl crt /etc/ssl/haproxy/ strict-sni alpn h2,http/1.1
the use of a directory here was deliberate - could you explain why changing to a single file is prefererable?

2022-03-25 15:41 UTC, villepeh commented
I think I got a bit too carried away with "what works for me" so I limited the changes to #12124 for now.

> unfortunately this is not secure, due to https://github.com/matrix-org/synapse/issues/9471 (for which fixes are welcome!) - option forwardfor makes haproxy append an entry to any existing X-Forwarded-For header, whereas synapse uses the first entry in the header.

Thanks for letting me know. This can be solved by adding "http-request del-header x-forwarded-for" before `option forwardfor`. But we might as well keep the original setting since it's just one line

> this is not a valid /.well-known/matrix/client file.
> Also: don't you need to set CORS headers for a client .well-known to work?

Thanks, I fixed mine :) I need to study more about CORS headers before I advising other server admins. I reverted this one.

> this isn't very clear. Why are we giving multiple options here? Which is the user supposed to do? (What was wrong with the original?)

I prefer local IPv6 traffic, because... uum... the future? 🙈  anyway, localhost is in half of the tutorials and 127.0.0.1 is in the other half so I kept that one here so it'll redirect traffic to whichever is listening.

> again, I don't think this is the place to be giving the user lots of different options. Let's make a single recommendation. If advanced users want to do things like restrict TLS versions they can research how to do it themselves.

Got carried away again. Sorry about hat

> the use of a directory here was deliberate - could you explain why changing to a single file is prefererable?

My distro doesn't have that folder so I thought it was just an example. I reverted it back. I created a _haproxy.key_ file that has cert.pem and fullchain.pem cat'd together. I reverted this one.

2022-03-26 09:07 UTC, villepeh commented
Localhost can actually cause issues in some scenarios: [resolver defaults to ipv6 even if local ipv6 not available in network stack](https://github.com/haproxy/haproxy/issues/508). Going back to 127.0.0.1.

2022-03-28 10:14 UTC, richvdh commented on changelog.d/12279.doc
> +HAProxy reverse proxy guide update to stop sending IPv4-mapped address to homeserver.
```suggestion
HAProxy reverse proxy guide update to stop sending IPv4-mapped address to homeserver. Contributed by @villepeh.
```

2022-03-28 10:15 UTC, richvdh approved these changes
nice and simple now! :heart:

2022-03-28 10:20 UTC, richvdh commented
> Signed-off-by: Villepeh

Just to make you aware, we normally need a legally identifiable name here (see https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off). Since this is a small change to the docs, I don't think it's too important for this PR, but if you make more contributions in future we'll need a legal name.

2022-03-28 10:48 UTC, merged