Implement MSC2815: allow room moderators to view redacted event content
matrix-org/synapse pull request #12427
Opened 2022-04-08 21:20 UTC by tulir

This pull request implements the query parameter described in MSC2815 to allow room moderators and server admins to get the original content of redacted events using the `/rooms/{roomId}/event/{eventId}` endpoint.

Signed-off-by: Tulir Asokan <tulir@maunium.net>

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [ ] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2022-04-12 18:04 UTC, squahtx requested changes
Looks good, just a few minor comments and questions

2022-04-12 18:04 UTC, squahtx commented on synapse/rest/client/room.py
> +            redact_level = event_auth.get_named_level(auth_events, "redact", 50)
I'm surprised we don't have a series of constants somewhere for "default-\<action\>-power-level"

2022-04-16 16:11 UTC, tulir commented on synapse/storage/databases/main/events_worker.py
> +        )
Indeed there can, there's an index on `redacts`, but I didn't notice that it wasn't a unique index.

I'm not sure if it there are cases where some `have_censored`s are false and some are true, but I changed the function to fetch all of them and return `any(values)` (so true if any are true, false if empty/all false)

2022-04-20 11:57 UTC, squahtx approved these changes
LGTM! Thanks for making the changes!

2022-04-20 11:57 UTC, merged