Add default_power_level_content_override config option.
matrix-org/synapse pull request #12535
Opened 2022-04-23 14:31 UTC by ara4n

Lets you override the default power levels for rooms created on this server, per
room creation preset.

Useful if you know that your users need special permissions in rooms
that they create (e.g. to send particular types of state events without
needing an elevated power level).  This takes the same shape as the
power_level_content_override parameter in the /createRoom API, but
is applied before that parameter.

This is something of a workaround in the absence of MSC3779 or MSC3761.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2022-04-23 14:41 UTC, ara4n commented
An example use of this would be something like:

```yaml
default_power_level_content_override:
  private_chat: { "events": { "com.example.foo" : 0 } }
  trusted_private_chat: { "events": { "com.example.foo" : 0 } }
  public_chat: { "events": { "com.example.foo" : 0 } }
```

...to let users in locally created rooms set `com.example.foo` state events without needing PL>0.

2022-04-29 14:25 UTC, squahtx commented on synapse/handlers/room.py
> +
The documentation for `default_power_level_content_override` says that it's applied before `power_level_content_override`, but here it is the other way around?

2022-04-29 14:25 UTC, squahtx commented on synapse/config/room.py
> +        #   private_chat: null
Some example non-null content might help admins understand what goes here:

```suggestion
        #   private_chat: { "events": { "com.example.foo" : 0 } }
```

2022-04-29 14:25 UTC, squahtx commented on synapse/handlers/room.py
> +                )
If an admin were to configure an override like: `private_chat: { "events": { "com.example.foo" : 0 } }`, the entire default `"events": {"m.room.name": ..., ...}` content from above will be replaced. Is this intended behaviour?

kind of related to https://github.com/matrix-org/matrix-spec/issues/492

2022-05-03 10:35 UTC, babolivier requested changes
I'd like to see a test for this change before we can merge the PR.

2022-05-03 10:42 UTC, DMRobertson commented
> I'd like to see a test for this change before we can merge the PR.

And an entry in the config manual too, please.

2022-05-04 08:17 UTC, andybalaam commented
I am attempting to address the comments here in https://github.com/matrix-org/synapse/pull/12618

2022-05-04 08:58 UTC, babolivier commented
> I am attempting to address the comments here in #12618

Closing in favour of #12618 then.

2022-05-04 08:58 UTC, closed without merging

2022-05-04 23:26 UTC, ara4n commented
sorry for completely missing this while travelling/catching up - @andybalaam thanks for taking it over.