make exceptions more explicit
matrix-org/synapse pull request #12675
Opened 2022-05-09 15:07 UTC by ShadowJonathan

Resolves https://github.com/matrix-org/synapse/issues/12662

This PR;
- Adds `exc_info=e`/`exc_info=True` in various areas where an exception being logged would be necessary
  - Optionally while also removing the `%s` string interpolation of the exceptions
- In some places, moves exception objects from being string-interpolated to be explicitly derived for re-raised exceptions (`from e`)

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

2022-05-10 08:50 UTC, erikjohnston reviewed
I think there are some valuable tidy ups in here, but I'm concerned by the sheer number of warnings we're making log a stack trace for. A general rule of thumb: warnings that should have stack traces should be errors. There are times when that is not necessarily the case (like I guess for some of the module API callbacks? But even then).

2022-05-10 08:50 UTC, erikjohnston commented on synapse/config/key.py
> +                    ) from e
I thing `from e` happens automatically in python3?

2022-05-10 08:50 UTC, erikjohnston commented on synapse/federation/sender/per_destination_queue.py
> +                exc_info=e,
So this is the sort of place where it really doesn't make much sense to include a stack trace. as its very common for remote servers to return non-200 responses. 

Plus, the stack trace doesn't tell us anything we don't already know at this stage.

2022-05-10 14:32 UTC, ShadowJonathan commented on synapse/config/server.py
> +            raise ConfigError("Failed to parse/validate server name") from e
Ah, i'll revert it then.

```suggestion
            raise ConfigError(str(e))
```

2022-05-10 14:32 UTC, ShadowJonathan commented on synapse/events/third_party_rules.py
> +                    "Failed to run module API callback %s:", callback, exc_info=e
It doesn't, but same rationale as comment above; to show in the diff where the `e` is going

2022-05-16 18:05 UTC, richvdh requested changes
can this be split up into smaller changes please

2022-05-22 15:54 UTC, ShadowJonathan commented
Marking as draft, as I need to split it and redo the changes, and that'll probably take a little while.

2022-08-16 13:10 UTC, richvdh commented
I'm going to close this PR because it needs substantial changes and it's bitrotting. If you're still interested in doing this work, please open smaller PRs!

2022-08-16 13:10 UTC, closed without merging