Fixup autotuning sample config
matrix-org/synapse pull request #12760
Opened 2022-05-17 11:01 UTC by erikjohnston

This was added in #12701

2022-05-17 11:12 UTC, richvdh requested changes

2022-05-17 11:12 UTC, richvdh commented on docs/sample_config.yaml
> +  # This flag enables cache autotuning, and is further specified by the
to me, "flag" is a boolean. None of these things are flags?  Not a major problem though.

2022-05-17 11:12 UTC, richvdh commented on docs/sample_config.yaml
>      #min_cache_ttl: 5m
what are the defaults for these things? (what happens if they are not set?) (also needs adding to the config manual I think)

2022-05-17 11:12 UTC, richvdh commented on docs/sample_config.yaml
>      #max_cache_memory_usage: 1024M
please could you document, here and in the config manual, what the valid suffixes are, and what they mean? (is M 1000000 or 1048576 ?)

2022-05-17 11:12 UTC, richvdh commented on docs/sample_config.yaml
> +  # This flag enables cache autotuning, and is further specified by the
s/flag/setting/ would be better, I think

2022-05-17 15:01 UTC, H-Shay commented
I can fix all this in the config manual, as it was on my agenda to rip out the config comments today anyway.

2022-05-18 02:58 UTC, H-Shay commented
The issues have hopefully been addressed here: https://github.com/matrix-org/synapse/pull/12776

I would say that this should be closed as I am in the process of deleting all comments from the config file as we speak.

2022-05-20 14:44 UTC, closed without merging