Fix invite notifications for users without pushers
matrix-org/synapse pull request #12840
Opened 2022-05-23 10:04 UTC by deepbluev7

fixes #12839

Signed-off-by: Nicolas Werner <nicolas.werner@hotmail.de>

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2022-05-23 10:11 UTC, deepbluev7 commented
If anyone remembers, why that condition was added in 2016, I would be open to hearing it. But it seems to just arbitrarily break the /notifications endpoint, if you don't register any pusher.

2022-05-23 10:21 UTC, babolivier requested changes
Thanks for the contribution! Could you add a test for it to ensure we don't accidentally break this in the future please?

2022-05-23 10:21 UTC, babolivier commented on changelog.d/12840.bugfix
> +Fix an issue introduced in Synapse 0.34 where /notifications would only return notifications if a user registered at least one pusher. Contributed by Famedly.
```suggestion
Fix an issue introduced in Synapse 0.34 where the `/notifications` endpoint would only return notifications if a user registered at least one pusher. Contributed by Famedly.
```

2022-05-23 10:22 UTC, babolivier commented
For the paper trail, this bug was introduced in https://github.com/matrix-org/synapse/commit/ed3979df5faac6d63990f4230662ff8cdcf59584

2022-05-23 10:24 UTC, deepbluev7 commented
Sure, let me try to add a test for that. Originally I wanted to add a sytest test, but... that looked like a lot of effort to synchronize the branches. I guess a unit test should work too.

2022-05-23 11:48 UTC, deepbluev7 commented
Added a testcase now. (Also verified that it fails without this change)

2022-05-23 11:56 UTC, deepbluev7 commented
The complement failure is a network error...

2022-05-30 11:14 UTC, babolivier approved these changes

2022-05-30 11:14 UTC, merged