Federation Sender & Appservice Pusher Stream Optimisations
matrix-org/synapse pull request #13251
Opened 2022-07-12 10:28 UTC by Fizzadar

Found this by accident while poking around on room creation optimisation; two things:

+ Use same get events stream DB query as the federation senders do in the appservice worker
  - this moves the AS pusher closer to the federation sender instances - which we'd like to setup to run multiple AS pushers in parallel just as you can fed senders
  - de-dupes the two near-identical functions into one for a bit of cleanup
+ Pull down event received TS in the stream query and thus remove the additional query to fetch this
  - the received TS is fetched per event processed by both of these workers, so this has potential to yield a significant reduction in query traffic depending on the synapse install/size/content

Signed off by Nick @ Beeper (@fizzadar)

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog).
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2022-07-14 12:17 UTC, richvdh requested changes
Looks like a nice cleanup, thanks!

A few minor tweaks

2022-07-14 14:59 UTC, Fizzadar commented on synapse/storage/databases/main/stream.py
> +    ) -> Tuple[int, List[EventBase], Dict[str, Optional[int]]]:
https://github.com/matrix-org/synapse/pull/13251/commits/c59d7173c7af8995f0f918f24fb35dbe9db637af

2022-07-14 14:59 UTC, Fizzadar commented on synapse/storage/databases/main/appservice.py
> +            desc="set_appservice_last_pos_txn",
Whoops typo'd! Fixed in https://github.com/matrix-org/synapse/pull/13251/commits/c59d7173c7af8995f0f918f24fb35dbe9db637af

2022-07-14 15:00 UTC, Fizzadar commented on synapse/storage/databases/main/appservice.py
>          )
Yep just switched to the simple query versions for consistency elsewhere, no functional change.

2022-07-14 15:01 UTC, Fizzadar commented on synapse/storage/databases/main/appservice.py
> +            desc="get_appservice_last_pos_txn",
Ah makes sense, noted for future! Fixed via https://github.com/matrix-org/synapse/pull/13251/commits/c59d7173c7af8995f0f918f24fb35dbe9db637af

2022-07-15 08:36 UTC, richvdh approved these changes
thanks!

2022-07-15 08:36 UTC, merged