Return 404 or member list when getting joined_members after leaving
matrix-org/synapse pull request #13374
Opened 2022-07-24 10:16 UTC by andrewdoh

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [ ] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2022-07-25 09:00 UTC, babolivier requested changes
Thanks for this contribution! I've noted a few things that I think need changing but overall it looks pretty good to me!

2022-07-25 09:00 UTC, babolivier commented on changelog.d/13374.bugfix
> +Fixed bug when user tries getting joined_members after already having left the room. Contributed by @andrewdoh.
```suggestion
Fix a bug introduced in Synapse 0.24.0 that would respond with the wrong error status code to `/joined_members` requests when the requester is not a current member of the room. Contributed by @andrewdoh.
```

2022-07-25 09:00 UTC, babolivier commented on tests/rest/admin/test_room.py
> +        channel = self.make_request("GET", url.encode("ascii"), access_token=user_tok_1)
```suggestion
        user = self.register_user("foo", "pass")
        user_tok = self.login("foo", "pass")
        room_id = self.helper.create_room_as(user, tok=user_tok)
        self.helper.leave(room_id, user, tok=user_tok)

        # delete the rooms and get joined roomed membership
        url = f"/_matrix/client/r0/rooms/{room_id}/joined_members"
        channel = self.make_request("GET", url.encode("ascii"), access_token=user_tok)
```

There are only one user and room in this test so let's not make it confusing by inferring there are more.

2022-07-25 09:00 UTC, babolivier commented on tests/rest/admin/test_room.py
> +        """Test that room members can be requested correctly"""
```suggestion
        """Test that requesting room members after leaving the room raises a 403 error."""
```

2022-07-25 09:00 UTC, babolivier commented on synapse/handlers/message.py
> +                    msg="Getting joined members after leaving is forbidden.",
The fact that the membership isn't `Membership.JOIN` doesn't necessarily mean the user has left the room (implying they have first joined it at some point). It just means you're not currently in the room (e.g. maybe you've never joined it, or you've been kicked, etc). This is kind of on the previous error message for getting it wrong though.
I would write something like "You must be a current member of the room to request its joined members." or "Getting joined members while not being a current member of the room is forbidden."

2022-07-25 09:21 UTC, DMRobertson commented on changelog.d/13374.bugfix
> +Fixed bug when user tries getting joined_members after already having left the room. Contributed by @andrewdoh.
```suggestion
Fix a bug introduced in Synapse 0.24.0 where responses to `/joined_members` requests would have the wrong HTTP status code when the requester is not a current member of the room. Contributed by @andrewdoh.
```

2022-08-03 12:25 UTC, babolivier approved these changes
Sorry about the delay - thanks for your contribution!

2022-08-03 12:26 UTC, merged

2023-04-21 11:29 UTC, DMRobertson commented
The PR title is

> Return 404 or member list when getting joined_members after leaving

But looking at the source this seems to only ever return 403 in this situation?