config: allow fnmatch wildcards in federation_domain_whitelist
matrix-org/synapse pull request #13424
Opened 2022-07-30 05:19 UTC by 3nprob

Resolves #7346

Allows to use built-in [`fnmatch`]() patterns in the whitelist:

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [ ] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2022-07-30 05:27 UTC, 3nprob commented
```
Signed-off-by: 3nprob <git@3n.anonaddy.com>
```

2022-07-30 05:51 UTC, 3nprob commented
Using `dict` as underlying makes less sense from a performance perspective after this change - I can change it to something more appropriate, shout out if you have any favorite datastructures for the job (and no we're not doing bloom filters :stuck_out_tongue_winking_eye: )

2022-07-30 06:47 UTC, 3nprob commented
Broke out `DomainGlobSet` (naming improvement suggestions welcome) to share implementation.

2022-08-02 11:41 UTC, richvdh requested changes
This looks like a sensible approach, thank you!

Some requests:
 * please could you give `DomainGlobSet` a docstring. What does it do, how should it be used?
 * please could you make sure that the new functionality gets some test coverage, to make sure it stays working. We'll need to test both inbound and outbound traffic: I suggest you look at `FederationClientTests` and `FederationServerTests` respectively.
 * please make sure the change to the config setting is documented in `docs/usage/configuration/config_documentation.md`.

2022-08-02 11:41 UTC, richvdh commented on synapse/config/_util.py
> +    @lru_cache(maxsize=100000)
suggest adding a comment here recording your notes about how `@lrucache` is good enough for now, but a future optimisation could be to use a tree.

2022-08-02 11:47 UTC, richvdh commented on synapse/crypto/context_factory.py
> +        )
sonarcloud wants you to write `x not in y` rather than `not (x in y)`

2023-01-25 19:31 UTC, clokep commented
I'm going to close this as the author has not responded; @3nprob if you're interested in continuing to work on this please let us know and respond to any outstanding feedback. Thank you!

2023-01-25 19:31 UTC, closed without merging

2023-03-17 04:47 UTC, 3nprob commented
Apologies for dropping the ball here.

FWIW the closed version still operates fine on a fork - anyone is free to extend this and resubmit it as a new PR. I may or may not get around to that some day if nobody else does.