Optimise async get event lookups
matrix-org/synapse pull request #13435
Opened 2022-08-02 14:49 UTC by Fizzadar

We turned on Redis get event caching... and it hammered the CPU! The huge number of lookups came from the roomember optimisation lookup (changed in https://github.com/matrix-org/synapse/commit/030888bbfb7a8b86b06910a79be719ae2a0a9fed). I also changed the get events function to prevent double lookups from any external cache there too (unconfirmed whether that had any impact, but seems sensible).

Signed off by Nick @ Beeper (@fizzadar).

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog).
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2022-08-03 09:42 UTC, richvdh requested changes
I'm afraid I bring problems rather than solutions, but let us know if you need a hand solving them.

2022-08-03 09:42 UTC, richvdh commented on synapse/storage/databases/main/events_worker.py
> +        event_map = self._get_events_from_local_cache(events, update_metrics=update_metrics)
it seems like we're going to end up updating the metrics on `_get_event_cache` twice here (though I'm rather wondering if a single set of metrics is actually meaningful for this two-level cache)

2022-08-03 09:42 UTC, richvdh commented on synapse/storage/databases/main/events_worker.py
> +            )
this looks like redundant work for cache implementations that *don't* have an external cache.

2022-08-03 09:42 UTC, richvdh commented on synapse/storage/databases/main/events_worker.py
> +        # out to any external cache for performance reasons.
add a note to say we check external caches later, in `get_missing_events_from_cache_or_db` ?

2022-08-03 09:42 UTC, richvdh commented on synapse/storage/databases/main/events_worker.py
> +                    # First fetch from the cache - including any external caches
we should note here that we've already checked the internal cache.

2022-08-03 09:42 UTC, richvdh commented on synapse/storage/databases/main/events_worker.py
>                      )
again this feels like redundant work on non-external-cache systems, and double-counting of metrics in any case.

2022-08-03 09:42 UTC, richvdh commented on synapse/storage/databases/main/events_worker.py
> +                    )
I think there's some redundant dict copying going on here:

```suggestion
                    missing_events = await self._get_events_from_cache(
                        missing_events_ids,
                    )
                    # Now actually fetch any remaining events from the DB
                    db_missing_events = await self._get_events_from_db(
                        missing_events_ids - missing_events.keys(),
                    )
```

2022-08-03 09:42 UTC, richvdh commented on changelog.d/13435.misc
> +Prevent unnecessary lookups to any external get event cache. Contributed by Nick @ Beeper (@fizzadar).
```suggestion
Prevent unnecessary lookups to any external `get_event` cache. Contributed by Nick @ Beeper (@fizzadar).
```

2022-08-03 18:38 UTC, Fizzadar commented
@richvdh thanks for the speedy review :) https://github.com/matrix-org/synapse/pull/13435/commits/d15b7c36997d851eb8e14073429b2343962d5d4a should address the duplicate work & double metric counting properly.

2022-08-04 12:07 UTC, richvdh approved these changes
lgtm otherwise!

2022-08-04 12:07 UTC, richvdh commented on synapse/storage/databases/main/events_worker.py
> +        # the `get_missing_events_from_cache_or_db` function below.
```suggestion
        # out to any external cache for performance reasons. The external cache is
        # checked later on in the `get_missing_events_from_cache_or_db` function below.
```

2022-08-04 12:07 UTC, richvdh commented on synapse/storage/databases/main/events_worker.py
> +                    # Try to fetch from any external cache, in-memory cache checked above
```suggestion
                    # Try to fetch from any external cache. We already checked the
                    # in-memory cache above.
```

2022-08-04 12:07 UTC, richvdh commented on synapse/storage/databases/main/events_worker.py
>          missing_event_ids = {e for e in events if e not in event_map}
I don't think this needs to be a set?

```suggestion
        missing_event_ids = (e for e in events if e not in event_map)
```

2022-08-04 14:49 UTC, merged