Add viewport directive to HTML templates to optimise for mobile
matrix-org/synapse pull request #13493
Opened 2022-08-10 14:30 UTC by gsouquet

This adds a meta viewport tag to the HTML templates so that the documents are scaled properly when viewed on mobile. And because an image is worth a thousand words, here's a GIF that illustrates the current problem

![validate-email](https://user-images.githubusercontent.com/769871/183927516-9b4e2926-8c65-4c08-99e3-848592c65e7d.gif)

Signed-off-by: Germain Souquet <germains@element.io>

### Pull Request Checklist

* [X] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2022-08-10 14:45 UTC, DMRobertson requested changes

2022-08-10 14:45 UTC, DMRobertson commented on synapse/res/templates/add_threepid_failure.html
> +    <title>request failed</title>
```suggestion
    <title>Request failed</title>
```

2022-08-10 14:45 UTC, DMRobertson commented on synapse/res/templates/password_reset_confirmation.html
> +<head>
Should this have a title? (Not sure if this is intended for use in emails)

The same for `password_reset_failure` and `password_reset_success` too.

2022-08-10 14:45 UTC, DMRobertson commented on synapse/res/templates/registration_failure.html
> +<head>
Should this have a `<title>`?

2022-08-10 14:45 UTC, DMRobertson commented
Otherwise LGTM!

2022-08-10 14:48 UTC, anoadragon453 requested changes
I've noticed while looking through that some pages set `user-scalable=no` in their viewport directive. This prevents users from zooming in on a page, and is considered bad for accessibility. We should fix this as well, though happy for it to be in a separate PR.

2022-08-10 14:48 UTC, anoadragon453 commented on changelog.d/13493.misc
> +Add viewport directive to HTML templates.
We try to keep our changelogs fairly sysadmin-friendly.

```suggestion
Modify HTML template content to better support mobile devices screen sizes.
```

2022-08-10 15:05 UTC, DMRobertson commented on changelog.d/13493.misc
> +Modify HTML template content to better support mobile devices screen sizes.
```suggestion
Modify HTML template content to better support mobile devices' screen sizes.
```

2022-08-10 15:06 UTC, DMRobertson approved these changes
Otherwise LGTM!

2022-08-11 13:04 UTC, anoadragon453 approved these changes

2022-08-11 13:04 UTC, merged