Delete push actions on receipt
matrix-org/synapse pull request #13834
Opened 2022-09-17 14:29 UTC by Fizzadar

Further work on optimising push action processing. Now that the push actions table is regularly summarised moving to delete-on-receipt seems appropriate.

I've not touched any of the receipt handling code in the event push actions store, or deleting from event push summary, both of which might be good future improvements?

Signed off by Nick @ Beeper (@fizzadar).

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog).
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2022-09-20 07:31 UTC, erikjohnston commented
Ah, alas we had to move away from this approach as on busy servers there was too much contention, resulting in lots of `could not serialize access due to concurrent update` errors (c.f. #13117)

2022-09-20 09:53 UTC, Fizzadar commented
@erikjohnston makes sense, although I was thinking for #13117 was that the contention is on the summary table rather than the push actions table?

2022-09-22 13:42 UTC, babolivier requested changes
The code lgtm, but I'd like to see a regression test for this (eg generating some push actions, sending a receipt and checking that the actions have been correctly deleted).

2022-09-24 08:52 UTC, Fizzadar commented
Test added in: https://github.com/matrix-org/synapse/pull/13834/commits/ef04bc876affde4280171033b92e3b2be12a2566, also caught a bug and added an additional test for that in https://github.com/matrix-org/synapse/pull/13834/commits/65b5bca6050538a6d0196e2206a23b4f287d82c5.

2022-09-24 11:02 UTC, Fizzadar commented
Merged in develop to fixup the receipts test, complement still flaking though but unrelated 😬!

2022-09-27 17:12 UTC, babolivier requested changes
> also caught a bug and added an additional test for that

Yay testing works :tada: 

It looks pretty much good to me apart from a few bits of documentation. I'd also like @erikjohnston to have a look since it sounded like he had concern last week.

2022-09-27 17:12 UTC, babolivier commented on tests/storage/test_receipts.py
> +                    keyvalues={"1": 1},
You can also just set `keyvalues` to `None` which generates an SQL query with no `WHERE` clause

2022-09-27 17:12 UTC, babolivier commented on tests/storage/test_receipts.py
> +    def test_receipts_clear_push_actions(self) -> None:
Could you add a docstring explaining what this test tests please? Same with the other test.

2022-09-27 18:08 UTC, clokep commented on synapse/storage/databases/main/receipts.py
> +            txn.execute(sql, (room_id, user_id, stream_ordering))
(Although right now we take this into account in #13878, not #13776)

2022-10-20 15:34 UTC, Fizzadar commented
Hm so the failing test here is a test that push a highlight action, which never gets cleared, but the test is selecting push actions over this time period (https://github.com/matrix-org/synapse/blob/da2c93d4b69200c1ea9fb94ec3c951fd4b424864/tests/storage/test_event_push_actions.py#L140).

Because they don't get deleted this means if a pusher fails for a bit once it recovers all highlight push actions will be notified, irrespective of read receipt position. The only way to maintain support for that situation is to check receipts at fetch time, so maybe there's no point in this 😩.

2022-12-12 11:42 UTC, Fizzadar commented
Based on my last comment about highlights also using the `event_push_actions` table I'm closing this as it's not going to remove any checks without moving highlights elsewhere which is a whole other thing (:

2022-12-12 11:42 UTC, closed without merging