Change default room version to 10. Implements MSC3904
matrix-org/synapse pull request #14111
Opened 2022-10-09 21:06 UTC by FSG-Cat

This PR implements MSC3904 and is not expected to be merged before MSC3904 has passed FCP. 

### Pull Request Checklist

* [X] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [X] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [X] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))
  
Signed-off-by: Catalan Lover <catalanlover@protonmail.com>

2022-10-10 08:50 UTC, DMRobertson requested changes
Blocked on https://github.com/matrix-org/matrix-spec-proposals/pull/3904#pullrequestreview-1135375408?

2022-10-10 08:50 UTC, DMRobertson commented on changelog.d/14111.doc
> +Change documentation to reflect that room version 10 is now default. Contributed by @FSG-Cat.
```suggestion
Mark [room version 10](https://spec.matrix.org/v1.4/rooms/v10/) as the default room version. Contributed by @FSG-Cat.
```

2022-10-10 08:50 UTC, DMRobertson commented on changelog.d/14111.feature
> +Make room version 10 default. Implements MSC3904. Contributed by @FSG-Cat.
```suggestion
Update the default room version to [v10](https://spec.matrix.org/v1.4/rooms/v10/) ([MSC 3904](https://github.com/matrix-org/matrix-spec-proposals/pull/3904)). Contributed by @FSG-Cat.

2022-10-10 08:50 UTC, DMRobertson commented on docs/usage/configuration/config_documentation.md
> +Currently defaults to "10".
```suggestion
Currently defaults to ["10"](https://spec.matrix.org/v1.4/rooms/v10/).

_Changed in Synapse X.Y:_ the default version room version was increased from [9](https://spec.matrix.org/v1.4/rooms/v9/) to [10](https://spec.matrix.org/v1.4/rooms/v10/).
```

2022-10-10 09:54 UTC, FSG-Cat commented
> Blocked on [matrix-org/matrix-spec-proposals#3904 (review)](https://github.com/matrix-org/matrix-spec-proposals/pull/3904#pullrequestreview-1135375408)?

Yes this PR is dependent on MSC3904 and that MSC is dependent on Conduit getting v10 support and enough time having passed after that point.

2023-01-04 12:22 UTC, clokep commented
@FSG-Cat Would you mind dusting this off now that the MSC is in FCP? I think we need to:

1. Merge in `develop`.
2. Update the changelog based on @DMRobertson's comment above: https://github.com/matrix-org/synapse/pull/14111#discussion_r991043401.
3. Re-request review on it (or shout here and one of us will put it back in the queue).

Thanks so much! 👍

2023-01-04 13:01 UTC, FSG-Cat commented
Ok so i fixed the problems i think but also i noticed the Synapse docs are very inconsistent in if they refer to latest spec or a spec version. I have decided that for my PR im linking to 1.5 as its the latest release but im sure that it might be a goal for another PR to go thru the docs and see what links need to be latest like for example known room versions might want to be latest and what links should be set manually if any. 

For example the text below is from the docs and its an example of where we use Explicit versions but in other places you can find latest references. 

> Client requests that invite user(s) when [creating a
room](https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3createroom)
will count against the `rc_invites.per_room` limit, whereas
client requests to [invite a single user to a
room](https://spec.matrix.org/v1.2/client-server-api/#post_matrixclientv3roomsroomidinvite)
will count against both the `rc_invites.per_user` and `rc_invites.per_room` limits.

2023-01-04 13:15 UTC, clokep commented
> im sure that it might be a goal for another PR to go thru the docs and see what links need to be latest like for example known room versions might want to be latest and what links should be set manually if any.

This sounds unrelated to this PR; if you wouldn't mind filing an issue that would be great!

2023-01-04 14:30 UTC, FSG-Cat commented
> > im sure that it might be a goal for another PR to go thru the docs and see what links need to be latest like for example known room versions might want to be latest and what links should be set manually if any.
> 
> This sounds unrelated to this PR; if you wouldn't mind filing an issue that would be great!

Oh yes i am sure its work for another PR i just wanted to write it down. And yes i will happily open an issue.

2023-01-09 12:33 UTC, clokep commented
This seems to have failing tests? Unsure if it is from this branch or not though.

2023-01-09 14:41 UTC, FSG-Cat commented
> This seems to have failing tests? Unsure if it is from this branch or not though.

Dendrite reported that they had an issue with Sytest failing due to it not knowing about v10. Not sure if that is related to the test failures. Like after all the only change this PR makes is making v10 default and well anyone who has run v10 default in production for the last few months like my self can tell this works.

2023-01-17 15:07 UTC, clokep commented
Sytest PR up at matrix-org/sytest#1328, once that merges we can kick off the builds again.

2023-01-18 16:14 UTC, clokep commented
@DMRobertson I think this will pass tests now! 👍

2023-01-18 16:20 UTC, DMRobertson approved these changes
Otherwise, I'm happy if CI is

2023-01-18 16:20 UTC, DMRobertson commented on docs/usage/configuration/config_documentation.md
> +_Changed in Synapse X.Y:_ the default version room version was increased from [9](https://spec.matrix.org/v1.5/rooms/v9/) to [10](https://spec.matrix.org/v1.5/rooms/v10/).
```suggestion
_Changed in Synapse 1.76:_ the default version room version was increased from [9](https://spec.matrix.org/v1.5/rooms/v9/) to [10](https://spec.matrix.org/v1.5/rooms/v10/).
```

2023-01-18 16:27 UTC, clokep commented on docs/usage/configuration/config_documentation.md
> +_Changed in Synapse X.Y:_ the default version room version was increased from [9](https://spec.matrix.org/v1.5/rooms/v9/) to [10](https://spec.matrix.org/v1.5/rooms/v10/).
Good catch!

2023-01-18 18:59 UTC, merged