Allow override for requesting specific worker types for Complement on command line.
matrix-org/synapse pull request #14324
Opened 2022-10-28 23:37 UTC by realtyem

## Why
Complement is great. It's really useful to test functionality. You can test monolith and workerised setups. But maybe the test I want to run doesn't need a full set of all types of workers, only the worker that targets a specific function or Servlet. Let's allow for overriding this at the command line level.

This means that if I wish to test that `federation_sender` functionality is correct with a worker, I wouldn't have to start up a bunch of extra workers. I could just run(for example):
```sh
POSTGRES=1 WORKERS=1 WORKER_TYPE="federation_sender" COMPLEMENT_DIR=../complement ./scripts-dev/complement.sh -run TestOutboundFederationSend
```
## Checklist
* [x] Add override functionality to `start_for_complement.sh`
* [x] Update docs to show how this works

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))
Signed-off-by: Jason Little <realtyem@gmail.com>

2022-10-29 13:30 UTC, dklimpel commented on docs/development/contributing_guide.md
> +  - If setting `WORKERS=1`, optionally set `WORKER_TYPES=` to declare which worker types you wish to test. A simple comma-delimited string containing the worker types defined from the template in [he
```suggestion
  - If setting `WORKERS=1`, optionally set `WORKER_TYPES=` to declare which worker
    types you wish to test. A simple comma-delimited string containing the worker types
    defined from the template in
    [here](https://github.com/matrix-org/synapse/blob/develop/docker/configure_workers_and_start.py).
    A safe example would be `WORKER_TYPES="federation_inbound,federation_sender,synchrotron"`.
    See the [worker documentation](../workers.md) for additional information on workers.
```

2022-11-04 16:37 UTC, reivilibre approved these changes

2022-11-04 16:43 UTC, reivilibre requested changes
Not really your fault, but do you think you could make `configure_workers_and_start.py` give an error if you try to create a worker type which isn't a real worker?
I specified `WORKER_TYPES=nonsense` and nothing stopped me. I worry this will lead someone to have a bad day if they make a typo.

2022-11-04 19:35 UTC, realtyem commented
It should already [log](https://github.com/matrix-org/synapse/blob/develop/docker/configure_workers_and_start.py#L424) a message that pops up from `configure_workers_and_start.py`. You think a hard stop would be better? I'll put it into #14294

2022-11-08 12:33 UTC, reivilibre commented
> It should already [log](https://github.com/matrix-org/synapse/blob/develop/docker/configure_workers_and_start.py?rgh-link-date=2022-11-04T19%3A35%3A02Z#L424) a message that pops up from `configure_workers_and_start.py`. You think a hard stop would be better? I'll put it into #14294

Yeah, I think a hard stop would be better because a mere log line is very easy to miss (especially in Complement output...) and arguably it renders the test null and void / it's not sensible to continue to test workers types that aren't understood.

2022-11-08 12:33 UTC, reivilibre approved these changes

2022-11-08 12:34 UTC, merged