Fix crash whenon admin media list api when info is None
matrix-org/synapse pull request #14537
Opened 2022-11-23 15:01 UTC by schmop

Signed-off-by: Lars Richard <lars.richard@rocketmail.com>

2022-11-23 15:02 UTC, schmop commented
Fixes #14536

2022-11-23 15:26 UTC, DMRobertson requested changes

2022-11-23 15:26 UTC, DMRobertson commented on synapse/storage/databases/main/room.py
> +                thumbnail_url = (content.get("info") or {}).get("thumbnail_url")
This only fixes the problem if `info` is falsey (i.e. a JSON `null`, `false`, `0` or `''`). If `info` is any other value that isn't an object (`true`, number, string, array) then the problem still endures.

Ideally, we would be rejecting events with malformed event content like this in the first place.

2022-11-23 15:26 UTC, DMRobertson commented on synapse/storage/databases/main/room.py
> +                thumbnail_url = (content.get("info") or {}).get("thumbnail_url")
I suggest doing something like

```python
info = content.get("info")
if isinstance(info, dict):
    thumbnail_url = info.get("thumbnail_url")
else:
    thumbnail_url = None
```

2022-11-24 10:48 UTC, DMRobertson approved these changes
Thank you!

2022-11-24 10:49 UTC, merged