Add `push.enabled` option to disable push notification calculation
matrix-org/synapse pull request #14551
Opened 2022-11-25 17:09 UTC by Half-Shot

This should short circuit calls to generate push notifications, for homeservers which don't make practical use of them. This is intended for the likes of things like t2bot.io and libera.chat.

2022-11-28 14:48 UTC, Half-Shot commented
Yish, this is more of a brute force "I don't want notifs to be calculated for any user ever" and that MSC is more opting out some users from notification calculations. 

I think the only practical difference is:

- This PR would save some DB calls to fetch the empty rulesets
- This PR would apply to all users regardless of their settings.

I'm personally still a bit partial to this solution existing in tandem with the MSC, as it still might be useful for debugging / performance purposes (we've disable notification calc via emergency patching in EMS before to debug performance issues and reduce strain in exceptional circumstances).

I will concede that there is overlap though.

2022-11-30 14:09 UTC, MatMaul requested changes

2022-11-30 14:09 UTC, MatMaul commented on docs/usage/configuration/config_documentation.md
> +   not interested in push/unread counters. This is enabled by default.
```suggestion
   not interested in push/unread counters. Push is enabled by default.
```

The wording doesn't really tell if you are talking about push itself or the option `enable_push`.

2022-12-01 07:48 UTC, MatMaul commented on docs/usage/configuration/config_documentation.md
> +   not interested in push/unread counters. This is enabled by default.
Sorry my comment is non sense since this is called `enable` and not `disable`...

2022-12-01 07:48 UTC, MatMaul approved these changes

2022-12-01 13:46 UTC, merged

2022-12-05 11:34 UTC, DMRobertson commented
Fixup in https://github.com/matrix-org/synapse/pull/14619