Added Command to export user data. Contributed by @thezaidbintariq
matrix-org/synapse pull request #14883
Opened 2023-01-21 10:34 UTC by thezaidbintariq

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [ ] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2023-01-21 13:28 UTC, thezaidbintariq commented
Sign-off-by: Zaid Bin Tariq ztariq.bscs19seecs@seecs.edu.pk

2023-01-21 14:06 UTC, clokep commented
Could you please add a change log file? It can be created as `changelog.d/14883.doc`. Thanks!

2023-01-21 14:24 UTC, thezaidbintariq commented
> Could you please add a change log file? It can be created as `changelog.d/14883.doc`. Thanks!

#14888 everything good now?

2023-01-21 15:58 UTC, dklimpel commented
You have to add the newsfile to this PR and not a separate PR.

2023-01-21 16:37 UTC, thezaidbintariq commented
> You have to add the newsfile to this PR and not a separate PR.
is it good now?

2023-01-21 16:56 UTC, dklimpel commented
> is it good now?

Yes.

2023-01-22 08:25 UTC, dklimpel requested changes

2023-01-22 08:25 UTC, dklimpel commented on docs/usage/administration/admin_faq.md
> +```python -m synapse.app.admin_cmd -c <config_file> export-data <user_id>
```suggestion
```console
python -m synapse.app.admin_cmd -c <config_file> export-data <user_id>
```

2023-01-22 08:25 UTC, dklimpel commented on changelog.d/14883.doc
> +Added command to export user data. Contributed by @thezaidbintariq
```suggestion
Added command to export user data. Contributed by @thezaidbintariq.
```

2023-01-22 08:39 UTC, dklimpel commented
Closes
- #14530

2023-01-22 23:18 UTC, dklimpel commented
IMHO there is also an optional parameter `--output-directory` for the directory.

https://github.com/matrix-org/synapse/blob/22cc93afe38d34c859d8863a99996e7e72ca1733/synapse/app/admin_cmd.py#L214-L217

2023-01-23 06:01 UTC, dklimpel commented
https://github.com/matrix-org/synapse/blob/22cc93afe38d34c859d8863a99996e7e72ca1733/.ci/scripts/test_export_data_command.sh#L21-L23

This is an example how to run with `poetry`.

2023-01-25 11:58 UTC, clokep commented on docs/usage/administration/admin_faq.md
> +Export data of specific user by running a python script that exports data and takes in user_id and config file as arguments.
```suggestion
Synapse includes a Python command to export data for a specific user. It takes the homeserver
configuration file and the full Matrix ID of the user to export:
```

2023-01-25 11:58 UTC, clokep commented on changelog.d/14883.doc
> +Added command to export user data. Contributed by @thezaidbintariq.
```suggestion
Document the export user data command. Contributed by @thezaidbintariq.
```

2023-01-25 12:01 UTC, merged