Fxing depreciated cmp argument
matrix-org/synapse pull request #14989
Opened 2023-02-04 12:33 UTC by handsanitizer77

Fixed remaining depreciated cmp arguments in attr decorators.
Improved code documentation and readability.

Signed-off-by: Ayush Srivastava <theotherguyasus@gmail.com>

2023-02-06 13:07 UTC, clokep commented
@handsanitizer77 This seems to include a significant number of unrelated changes to what is proposed in the PR description (e.g. formatting and whitespace changes). Could you back out those changes to just the `cmp` changes to `attr` functions please?

2023-02-06 13:07 UTC, clokep requested changes
Unrelated changes.

2023-02-07 18:33 UTC, handsanitizer77 commented
I've added/removed the additional changes. Please go through the same.
@clokep

2023-02-07 18:39 UTC, DMRobertson commented
> This seems to include a significant number of unrelated changes to what is proposed in the PR description (e.g. formatting and whitespace changes).

The latest commit still suffers from this problem; it is very hard for us to see what has actually changed from the [diff](https://github.com/matrix-org/synapse/pull/14989/files).

Please follow the [Synapse contribution guide](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html) to setup a development environment, then `poetry run scripts-dev/lint.sh` script to format your changes.

2023-02-07 18:40 UTC, DMRobertson commented
Additionally, there now a number of merge conflicts---please take a look at resolving them. If in doubt, use the version from `develop`.

2023-02-07 21:15 UTC, squahtx commented
Please re-request review from synapse-core once the PR has been cleaned up.

2023-02-13 14:11 UTC, closed without merging