Admin API endpoint to delete a reported event
matrix-org/synapse pull request #15116
Opened 2023-02-21 07:00 UTC by dklimpel

Closes #15011

Add admin API endpoint to delete a reported event.

Move `get_event_report` and `get_event_reports_paginate` from `RoomStore` to `RoomWorkerStore`.
Both are read only queries. IMO there is no reason why this is should not possible for workers.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

Signed-off-by: Dirk Klimpel [5740567+dklimpel@users.noreply.github.com](mailto:5740567+dklimpel@users.noreply.github.com)

2023-02-23 20:47 UTC, H-Shay commented
Looks like there is a merge conflict, would you mind resolving that before review?

2023-02-27 14:10 UTC, DMRobertson requested changes
> Move get_event_report and get_event_reports_paginate from RoomStore to RoomWorkerStore.
Broadly LGTM, but I've left a few notes.

> Both are read only queries. IMO there is no reason why this is should not possible for workers.

Agreed on this, but if possible could you try to keep this to a separate commit (or even PR) in future? It's helpful for the reviewer (if independent changes are separate.)

2023-02-27 14:10 UTC, DMRobertson commented on tests/rest/admin/test_event_reports.py
> +        self.url = "/_synapse/admin/v1/event_reports/2"
Can we avoid hard coding this by making `add_event_report` return `next_id` and reading that value here?

2023-02-27 14:10 UTC, DMRobertson commented on tests/rest/admin/test_event_reports.py
> +        self.assertEqual({}, channel.json_body)
This test should check that the delete actually took place in the database by trying to fetch it again, e.g. by calling `RoomStore.get_event_report`. Alternatively you could make an admin API request to fetch the event and check that it fails in a sensible way.

2023-02-27 14:59 UTC, dklimpel commented
> Agreed on this, but if possible could you try to keep this to a separate commit (or even PR) in future? It's helpful for the reviewer (if independent changes are separate.)

I have moved it to #15165

2023-02-28 12:08 UTC, DMRobertson approved these changes
Thanks Dirk, LGTM!

2023-02-28 12:08 UTC, DMRobertson commented on synapse/storage/databases/main/room.py
> +            received_ts: Time when the user submitted the report.
```suggestion
            received_ts: Time when the user submitted the report (milliseconds).
```

2023-02-28 12:09 UTC, merged