Allow OIDC token response `id_token` to be an empty string
matrix-org/synapse pull request #15322
Opened 2023-03-24 20:26 UTC by jaywink

Mattermost seems to respond with an empty `id_token` string as it has that in the shared data model with its consumer OpenID implementation. This causes Synapse to think it needs to validate it even though Mattermost doesn't support it.

Allow an empty string, not just not being defined.

Add also example documentation to using Mattermost as an OAuth2 provider.

Refs: https://github.com/matrix-org/synapse/issues/12980#issuecomment-1483286992

Signed-off-by: Jason Robinson <mail@jasonrobinson.me>

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [ ] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [ ] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2023-03-27 11:22 UTC, clokep commented
@sandhose I'd be curious of your thoughts on this -- does it seem reasonable?

2023-03-27 14:04 UTC, sandhose commented
That feels like a bad implementation on the Mattermost side, to be honest… If we choose to sidestep their buggy implementation, I'd rather have a "skip ID token verification" flag on the provider config instead of accepting empty strings for the `id_token`

2023-03-30 08:55 UTC, MatMaul requested changes
@jaywink I am putting that PR on `request changes` following @sandhose comment.

2023-12-09 19:28 UTC, jaywink commented
Sorry for forgetting about this. I'll open a bug on Mattermost side and maintain the patch separately until it's fixed :+1:

2023-12-09 19:28 UTC, closed without merging