Update the check_schema_delta script to account for when the schema version has been bumped locally
matrix-org/synapse pull request #15466
Opened 2023-04-20 20:38 UTC by H-Shay

Previously, the script used the schema version on develop as the canonical version, so if your PR bumped the schema version and put schema delta files in the folder corresponding to the new schema version it would fail the CI check.

This PR addresses that by checking to see if the schema version is changed locally, and if it is, uses the local version as the canonical schema version number. 

I'm new to the python git library so there may be a more elegant way to do this but I did test it locally and afaict it does work.

2023-04-21 11:17 UTC, DMRobertson commented on scripts-dev/check_schema_delta.py
To summarise,  we previously enforced (and continue to enforce) the invariant

> PRs can only introduce migrations for the current schema

but we have now altered "current schema" to mean the PR's current schema version, falling back to develop's schema version.

I think we ought to have a check which enforces that the PR's schema version is either (develop's schema version) or (develop's schema version + 1). That would prevent the following footgun:

- Develop is on schema version 1.
- Someone opens PR X which bumps the schema version from 1 to 2. We ignore it for ages.
- Develop sees several schema updates. It's now on schema 5.
- We rerun the CI for PR X which still targets version 2. 
- It passes.
- :warning: We merge in new migrations to schema delta 2, after it should have been frozen!

2023-04-21 11:17 UTC, DMRobertson requested changes
See comment. (Do you agree with my reasoning?)

2023-04-21 15:23 UTC, H-Shay commented
Makes sense to me and I even think you mentioned this in the meeting but it didn't fully register for some reason - I will update this to implement the check you've outlined, thanks for taking a look!

2023-04-21 20:43 UTC, H-Shay commented
I've added a check that determines if the proposed schema version is +/- 1 from the schema version on develop (-1 I added so it doesn't irritatingly break when something needs to be reverted) before then using the local version as the canonical version if it passes. Hopefully this addresses your concern?

2023-04-24 10:30 UTC, erikjohnston commented on scripts-dev/check_schema_delta.py
> +            )
I think instead of looping through the diff we can just read the local file in the checkout? Which will be the merge commit?

2023-04-25 17:48 UTC, DMRobertson approved these changes
I suspect there are edge cases around all this (e.g. reverting the schema to version N-1 and adding new migrations to schema N - 1 is permitted by this check, but would be Very Bad if we ever released a Synapse with schema version N).

But this doesn't have to perfectly encapsulate all of the schema constraints to be useful. :+1:

(Have you tried merging this into your other PR to check that its CI would then run after this change?)

2023-04-25 18:52 UTC, merged

2023-04-25 18:53 UTC, H-Shay commented
Merged #15466 into develop.