fix: check authdict before accessing any attribute
matrix-org/synapse pull request #16153
Opened 2023-08-22 05:30 UTC by prajjawal05

Fixes: https://github.com/matrix-org/synapse/issues/15871

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
  - Feel free to credit yourself, by adding a sentence "Contributed by @github_username." or "Contributed by [Your Name]." to the end of the entry.
* [x] Pull request includes a [sign off](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#sign-off)
* [x] [Code style](https://matrix-org.github.io/synapse/latest/code_style.html) is correct
  (run the [linters](https://matrix-org.github.io/synapse/latest/development/contributing_guide.html#run-the-linters))

2023-08-22 05:35 UTC, prajjawal05 commented
Signed-off-by: Prajjawal Agarwal prajjawalagarwal@gmail.com

2023-08-22 12:09 UTC, clokep requested changes
This is very similar to #15944 and I don't think correct. If this is not a dict it should likely *error* not just silently ignore the invalid data.

We also want to do the checking *up front* on the REST endpoints so that at this point we *know* we have good data.

2023-08-23 08:29 UTC, closed without merging

2023-08-23 11:29 UTC, clokep commented
> I will close this PR, and let all conversations be in the PR which you mentioned. Thanks for checking this!

The person who put up #15944 has stopped responding FWIW, so it is likely fine for you to take a crack at it.

2023-08-23 20:12 UTC, prajjawal05 commented
I will look at it thanks!