Update debian systemd service to use Type=notify
matrix-org/synapse pull request #8169
Opened 2020-08-25 23:14 UTC by dalcde

This ensures systemctl start matrix-synapse returns only after synapse
is actually started, which is very useful for automated deployments.

Fixes #5761

2020-08-26 12:15 UTC, richvdh requested changes

2020-08-26 12:15 UTC, richvdh commented on changelog.d/8169.feature
> +Use Type=notify in debian systemd service.
changes to the debian packaging go in the `debian/changelog` file, not here: please could you move this?

(there are some notes in CONTRIBUTING.rst)

2020-08-26 12:16 UTC, clokep commented
See [the docs](https://www.freedesktop.org/software/systemd/man/systemd.service.html#Type=) for an explanation.

> it is expected that the service sends a notification message via `sd_notify(3)` or an equivalent call when it has finished starting up. systemd will proceed with starting follow-up units after this notification message has been sent.

Is this true, does synapse fire this?

2020-08-26 12:18 UTC, richvdh commented
@clokep yes it does!

2020-08-26 12:38 UTC, dalcde commented
In fact, Type=notify is already used by contrib/systemd/matrix-synapse.service

2020-08-26 12:44 UTC, dalcde commented
Done. I accidentally squashed my commits, but I hope it isn't causing
too much trouble for a one-line change.

2020-08-26 18:03 UTC, richvdh requested changes
sorry, it looks like you've picked up a broken version of `develop`. could you merge the latest version?

2020-08-26 23:08 UTC, dalcde commented
Done

2020-08-27 09:39 UTC, richvdh approved these changes
thanks!

2020-08-27 09:39 UTC, merged