Update test logging to be able to accept braces
matrix-org/synapse pull request #8335
Opened 2020-09-17 09:49 UTC by ShadowJonathan

The old method simply replaced braces with parentheses before sending it off into twisted logging, this was a hack, it's now been properly fixed.

The reason why the hack is needed, and this roundabout is needed, is because twisted logging works with "new-style formatting" (PEP 3101), or simply "brace formatting" (`"{thing}".format({thing=1})`), if braces were preserved (in what is essentially the "format" string), the twisted logger will attempt to interpret them according to the new-style formatting, and produce an error.

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

`Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>`

2020-09-17 21:18 UTC, clokep commented
`tests/utils.py` seems to have the same functions in it. We should update that too (or remove it if it is unnecessary?)

2020-09-17 21:18 UTC, clokep requested changes
Per my comment above.

2020-09-18 11:12 UTC, ShadowJonathan commented
@clokep the only relevant call i could find it `_format_call`, which doesn't do something like this. Could you point me to the exact lines that do this? I can't seem to find them in `tests.utils` or anywhere else under `tests/` at this point.

2020-09-18 11:27 UTC, clokep commented
> @clokep the only relevant call i could find it `_format_call`, which doesn't do something like this. Could you point me to the exact lines that do this? I can't seem to find them in `tests.utils` or anywhere else under `tests/` at this point.

Doh. PyCharm pulled up a symbol from [a different project](https://github.com/matrix-org/sydent/blob/66abd5b6808cd9e15e62e88000ec7e5afc287d56/tests/utils.py#L234-L245) and I didn't notice! Sorry about that.

2020-09-18 11:35 UTC, ShadowJonathan commented
I'll open up an issue there that mirrors this fix :+1:

2020-09-18 11:42 UTC, clokep approved these changes

2020-09-18 11:56 UTC, merged