Include user agent in user daily visits table
matrix-org/synapse pull request #8503
Opened 2020-10-08 17:24 UTC by neilisfragile

2020-10-08 18:06 UTC, clokep commented on synapse/storage/databases/main/schema/delta/59/02drop_unused_stream_tables.sql
> +DROP table account_data_max_stream_id;
I think you'll want `IF EXISTS` on each of these to help out CI.

2020-10-09 09:30 UTC, erikjohnston requested changes

2020-10-09 09:30 UTC, erikjohnston commented on synapse/storage/databases/main/metrics.py
> +                    SELECT u.user_id, u.device_id, ?, u.user_agent
This isn't in the `GROUP BY` clause, and in general there may technically be multiple user agents associated with a device so we'll need to decide which one to record. In an ideal world I'd probably say we should do one of:

1. record every UA and make the useragent column an array (but that doesn't work on sqlite, and may make processing harder);
2. record the UA that we saw the most, but that probably involves complicated SQL; or
3. take the most recent UA we saw (easy on postgres, hard on sqlite).

All of which sound like faff, so assuming that we don't really care too much which one we pick I'd probably do `MAX(u.user_agent)`. 

(Note, this query probably works fine on SQLite as it allows adding columns not in the GROUP BY clause, it'll return an entry from a random row, but postgres refuses to allow it).

2020-10-12 10:54 UTC, erikjohnston approved these changes

2020-10-12 10:54 UTC, erikjohnston commented on synapse/storage/databases/main/metrics.py
> +                    SELECT u.user_id, u.device_id, ?, MAX(u.user_agent)
If you could just add a comment about the SQL to say why its fine to take the MAX that would be great

2020-10-15 09:36 UTC, merged