Add admin APIs to allow server admins to list users' pushers
matrix-org/synapse pull request #8610
Opened 2020-10-20 19:13 UTC by dklimpel

Add an admin API `GET /_synapse/admin/v1/users/<user_id>/pushers`
like https://matrix.org/docs/spec/client_server/latest#get-matrix-client-r0-pushers

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [x] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

Signed-off-by: Dirk Klimpel dirk@klimpel.org

2020-10-26 14:00 UTC, erikjohnston requested changes
Looks good, just some nits.

2020-10-26 14:00 UTC, erikjohnston commented on synapse/rest/admin/users.py
> +class PushersRestServlet(RestServlet):
Can you add a docstring to briefly explain what it is and the request/response please?

2020-10-26 14:00 UTC, erikjohnston commented on synapse/rest/admin/users.py
> +    async def on_GET(self, request, user_id):
We've been really bad at asking for this, but can you add type hints here please? The idea is really that new code should be typed where possible

```suggestion
    async def on_GET(self, request: SynapseRequest, user_id: str) -> Tuple[int, JsonDict]:
```

Or something, you'll need to import those types.

2020-10-26 14:00 UTC, erikjohnston commented on synapse/rest/admin/users.py
> +ALLOWED_KEYS = {
```suggestion
_GET_PUSHERS_ALLOWED_KEYS = {
```

2020-10-26 14:00 UTC, erikjohnston commented on synapse/rest/admin/users.py
> +            {k: v for k, v in p.items() if k in ALLOWED_KEYS} for p in pushers
```suggestion
            {k: v for k, v in p.items() if k in _GET_PUSHERS_ALLOWED_KEYS} for p in pushers
```

2020-10-26 18:26 UTC, erikjohnston commented
Thanks! Looks like there is a merge conflict?

2020-10-26 19:59 UTC, dklimpel commented
> Thanks! Looks like there is a merge conflict?

I have solved the conflict. To many merges at the same day.  😄

2020-10-28 15:01 UTC, erikjohnston approved these changes

2020-10-28 15:02 UTC, erikjohnston commented
> > Thanks! Looks like there is a merge conflict?
> 
> I have solved the conflict. To many merges at the same day.

There's been so many good PRs that I completely forgot I hadn't merged this one :D

2020-10-28 15:02 UTC, merged