Add basic SAML tests for mapping users.
matrix-org/synapse pull request #8800
Opened 2020-11-23 18:35 UTC by clokep

This adds some basic tests for SAML. This specifically aims to partially test the `_map_saml_response_to_user` method.

2020-11-23 18:36 UTC, clokep commented
This was originally part of #8774. Unfortunately this will fail since libxmlsec is missing from our Buildkite images.

2020-11-25 21:34 UTC, clokep commented
I wonder if we need to skip these tests if the package isn't found properly? Packagers might be unhappy otherwise.

2020-12-01 17:39 UTC, richvdh requested changes
a few nits

2020-12-01 17:39 UTC, richvdh commented on tests/handlers/test_saml.py
> +        config["saml2_config"] = saml_config
the normal way to do this is to override `default_config` and let `setup_test_homeserver` call it.

2020-12-01 17:39 UTC, richvdh commented on tests/handlers/test_saml.py
> +        self.handler = SamlHandler(hs)
is using our own `SamlHandler` (as opposed to the singleton `hs.get_saml_handler()`) deliberate?

2020-12-01 17:39 UTC, richvdh commented on tests/handlers/test_saml.py
> +        self.http_client.user_agent = "Synapse Test"
is this ever actually called? we don't seem to set up any results for `get_json` so I suspect not, in which case can we omit it, at least until it's needed?

2020-12-01 17:39 UTC, richvdh commented on tests/handlers/test_oidc.py
> +        # Register all of the potential usernames for a particular username.
```suggestion
        # Register all of the potential mxids for a particular OIDC username.
```

(similarly for SAML)

2020-12-01 18:11 UTC, clokep commented on changelog.d/8800.misc
> +Add tests for SAML integration.
```suggestion
 Add additional error checking for OpenID Connect and SAML mapping providers.
```

2020-12-01 18:34 UTC, clokep commented
Thanks for the review! Most of the comments were also applicable to the OIDC tests (which the SAML tests heavily cribbed from). I applied the requested changes to both test files!

2020-12-02 10:54 UTC, richvdh approved these changes
lgtm

2020-12-02 12:09 UTC, merged