Don't register GaugeBucketCollector metric until data is present
matrix-org/synapse pull request #8926
Opened 2020-12-11 12:09 UTC by anoadragon453

Fixes https://github.com/matrix-org/synapse/issues/8792.

This PR modifies `GaugeBucketCollector` to wait until it has data to report before registering itself. Otherwise we end up initially reporting empty values on Synapse startup.

I'm actually not sure whether delaying registration is the best approach. Or if there's a way to register, yet hold off on reporting until we have some useful data instead.

2020-12-16 18:04 UTC, richvdh requested changes
seems reasonable.

> Or if there's a way to register, yet hold off on reporting until we have some useful data instead.

Yes, an alternative approach which I think would be simpler would be to initialise `self._metric` to `None`, and make the yield in `collect` conditional. Then you don't need to worry about delaying registration.

2020-12-16 19:45 UTC, erikjohnston commented
I think prometheus might do something unhelpful if you don't report metrics? Something like using the last known value? There's something odd like that, but I can't remember what

2020-12-16 21:46 UTC, richvdh commented
> Something like using the last known value?

That would probably be fine here...

2021-04-06 12:57 UTC, richvdh approved these changes
lgtm otherwise

2021-04-06 12:57 UTC, richvdh commented on changelog.d/8926.bugfix
> +Prevent `synapse_forward_extremities` and `synapse_excess_extremity_events` metrics from initially reporting zero-values after startup.
```suggestion
Prevent `synapse_forward_extremities` and `synapse_excess_extremity_events` Prometheus metrics from initially reporting zero-values after startup.
```

2021-04-06 12:58 UTC, richvdh commented
actually: can you update the PR summary and description to reflect the updated approach, please?

2021-04-06 15:32 UTC, merged