Test OIDC login with multiple OIDC providers
matrix-org/synapse pull request #9127
Opened 2021-01-15 18:17 UTC by richvdh

The idea here is to make sure that an OIDC login works correctly when more than one OIDC provider is configured. It extends the existing `MultiSSOTestCase.test_multi_sso_redirect_to_oidc` testcase into a full OIDC login test.

There are three commits here: probably easiest to review individually.

2021-01-15 18:59 UTC, clokep requested changes
This looks fine, but tests are failing on Py3.5.

2021-01-17 20:01 UTC, richvdh commented
it's failing due to a bug fixed in #9128 (which is why that's passing despite being based on this branch). I could shuffle the PRs around a bit to get them to both pass, but it's likely to be a bit fiddly. wdyt?

2021-01-18 13:07 UTC, clokep commented
> turns out it's failing due to a bug fixed in #9128 (which is why that's passing despite being based on this branch). I could shuffle the PRs around a bit to get them to both pass, but it's likely to be a bit fiddly. wdyt?

I'll take a look at that shortly then! 👍

2021-01-18 14:54 UTC, richvdh commented
I've squash-merged #9128, which is a superset of the changes in this PR, thus ensuring we don't have a commit on develop which breaks the tests.

The two PRs are somewhat related anyway.

2021-01-18 14:54 UTC, closed without merging