Allow testing old deps with postgres
matrix-org/synapse pull request #9206
Opened 2021-01-22 10:33 UTC by erikjohnston

This is so that we can test old dependencies with postgres

2021-01-22 19:00 UTC, clokep commented on tox.ini
> +    # Also strip out psycopg2 unless we need it.
This is to ensure that we don't import it when it isn't available?

2021-01-25 12:13 UTC, richvdh requested changes

2021-01-25 12:13 UTC, richvdh commented on .buildkite/scripts/setup_old_deps.sh
>  export LANG="C.UTF-8"
this export goes nowhere. I suspect it was here for a reason; you'll need to figure out if that reason was important.

2021-01-25 12:13 UTC, richvdh commented on .buildkite/scripts/setup_old_deps.sh
> -exec tox -e py35-old,combine
there are comments in the header which will need updating.

2021-01-25 12:13 UTC, richvdh commented on tox.ini
> +
I believe this should be magically inherited from the defaults in `testenv`. could you verify one way or the other?

2021-02-24 11:47 UTC, closed without merging