config: Add detail to auto_join_rooms comment
matrix-org/synapse pull request #9291
Opened 2021-02-02 03:51 UTC by dykstranet

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

2021-02-02 11:38 UTC, anoadragon453 approved these changes
Important gotcha to call out, thanks!

Test failures were unrelated to the contents of this PR.

2021-02-02 11:38 UTC, anoadragon453 commented on synapse/config/registration.py
> +        # who knows the room's link, including guests' to access the room.
This is very helpful, though I'm afraid Element is only one client in the Matrix ecosystem, and we try to be client-agnostic in Synapse.

The requirement for the room is to be publicly joinable (have a join rule of `public` set). Additionally one doesn't need to allow guest access to the room.

```suggestion
        # room. The join rule of the room must be set to 'public'.
```

While I'd like to make this as easy as possible for people to use, client-specific instructions are best suited to a client-specific guide.

2021-02-02 11:38 UTC, anoadragon453 commented on changelog.d/9291.doc
> +Add configuration detail to auto_join_rooms comment.
```suggestion
Add note to `auto_join_rooms` config option explaining existing rooms must be publicly joinable.
```

2021-02-02 11:38 UTC, anoadragon453 requested changes
That was meant to be a change request :)

2021-02-03 05:21 UTC, dykstranet commented
@anoadragon453 Thank you for your suggestion, I have applied these changes. Feel free to squash the PR.

2021-02-03 15:21 UTC, anoadragon453 approved these changes
lgtm, thank you!

2021-02-03 15:21 UTC, merged