Add -prof tox environment
matrix-org/synapse pull request #9293
Opened 2021-02-02 09:14 UTC by ShadowJonathan

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

Signed-off-by: Jonathan de Jong <jonathan@automatia.nl>

2021-02-02 09:18 UTC, ShadowJonathan commented
(I *think* it would also be handy to add this to `CONTRIBUTING.md`, but i have no idea how to go about that when #9281 is also going on)

2021-02-10 19:56 UTC, richvdh reviewed
I'm not really convinced this is worthwhile: it's just extra stuff to maintain, which isn't going to be used very often. I think if you're going to run a profiler, you can run `trial` yourself.

2021-02-10 19:57 UTC, richvdh requested changes
.

2021-02-11 07:34 UTC, ShadowJonathan commented
How exactly would this add maintenance load? The only thing I can imagine is a gotcha for "oh, so I can just ignore `!prof`", this change will only make it so that *any* test run is able to be profiled (which can be helpful if it's included in the tox config by default), which can then be added to `CONTRIBUTING.md`. Synapse swapped out plainly running `trial` with deterministic `tox`, adding a profiler option to it would only make sense, as every other option has already been folded into `tox`.

I understand if y'all dont wanna accept this PR, but if you really just wanna put a full dot on that decision, just close it.

2021-02-11 12:21 UTC, clokep commented
> How exactly would this add maintenance load? The only thing I can imagine is a gotcha for "oh, so I can just ignore `!prof`" when reading `tox.ini`

tox configs are already confusing enough to read and this adds additional cognitive load each time we need to modify it.

> Synapse swapped out plainly running `trial` with deterministic `tox`, adding a profiler option to it would only make sense, as every other option has already been folded into `tox`.

I'm not sure what this means, I think most of the team runs tests directly via trial (and not using tox).

I agree with @richvdh's assessment.

2021-02-11 12:21 UTC, closed without merging