Complete Apache instructions
matrix-org/synapse pull request #9517
Opened 2021-03-01 18:26 UTC by crees

Do I still need a CHANGELOG entry for a docs fix?

2021-03-01 19:02 UTC, clokep commented
> Do I still need a CHANGELOG entry for a docs fix?

They're preferred, yes. It helps people realize the docs were updated when taking a look at the release notes.

2021-03-03 12:06 UTC, crees commented
Changelog entry done.

2021-03-05 12:19 UTC, anoadragon453 requested changes
A minor change and a question, but otherwise lgtm. Learned a bit about Apache in the process too :slightly_smiling_face:

2021-03-05 12:19 UTC, anoadragon453 commented on docs/reverse_proxy.md
> +Listen 8448
Just for my own curiosity, this is indeed required as per https://httpd.apache.org/docs/2.4/bind.html.

> To implement a VirtualHost, the server must first be told to listen to the address and port to be used. Then a <VirtualHost> section should be created for the specified address and port to set the behavior of this virtual host. Note that if the <VirtualHost> is set for an address and port that the server is not listening to, it cannot be accessed.

2021-03-05 12:19 UTC, anoadragon453 commented on docs/reverse_proxy.md
> -    ServerName matrix.example.com;
Thanks for catching, `;` are indeed not a thing in Apache configs. And indeed https://httpd.apache.org/docs/2.4/mod/core.html#servername mentions to include a port for `ServerName` if possible:

> For optimal reliability and predictability, you should specify an explicit hostname and port using the ServerName directive.

2021-03-05 12:19 UTC, anoadragon453 commented on docs/reverse_proxy.md
> +and `mod_lbmethod_byrequests`.
`mod_proxy_balancer` and `mod_lbmethod_byrequests` are likely only required if you require load balancing, which this example doesn't specify?

2021-03-05 12:19 UTC, anoadragon453 commented on changelog.d/9517.doc
> +Complete instructions for Apache proxying
You will need to add punctuation (just a period) to the end of this changelog entry.

2021-04-09 11:04 UTC, anoadragon453 commented
Hey @crees, are you still up for helping drive this PR home?

2021-06-02 14:25 UTC, richvdh commented
This seems to only need trivial changes, so I'll try and bring it up to date.

2021-06-02 14:27 UTC, richvdh commented
actually it seems to have been superceded by #9696, so I'm going to close it.

2021-06-02 14:27 UTC, closed without merging