Add Kong reverse proxy example
matrix-org/synapse pull request #9704
Opened 2021-03-27 06:18 UTC by f35f0ef9d0e827dae86552d3899f78fc

### Pull Request Checklist

* [ ] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [ ] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [ ] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

2021-03-29 13:52 UTC, anoadragon453 requested changes
Thank you for your contribution! This looks good to me on the whole, just a few tweaks as noted below.

2021-03-29 13:52 UTC, anoadragon453 commented on docs/reverse_proxy.md
> +    - /_synapse/client
This also covers `/_matrix/federation/...` routes (server<->server communication), so `synapse-client-route` may be slightly misleading. Perhaps `synapse-public-route` instead?

2021-03-29 13:52 UTC, anoadragon453 commented on README.rst
> +`Kong <https://docs.konghq.com/getting-started-guide/2.3.x/overview/>`_,
```suggestion
`Kong <https://docs.konghq.com/getting-started-guide/latest/overview/>`_,
```

This works as well and wouldn't need to be maintained :slightly_smiling_face:

2021-03-29 13:52 UTC, anoadragon453 commented on changelog.d/9704.doc
> +Add Kong reverse proxy example.
```suggestion
Add Kong reverse proxy config example.
```

2021-03-29 13:52 UTC, anoadragon453 commented on docs/reverse_proxy.md
> +[DB-less configuration format](https://docs.konghq.com/gateway-oss/2.3.x/db-less-and-declarative-config/).
```suggestion
[DB-less configuration format](https://docs.konghq.com/gateway-oss/latest/db-less-and-declarative-config/).
```

and here.

2021-03-30 01:47 UTC, f35f0ef9d0e827dae86552d3899f78fc commented
> Thank you for your contribution! This looks good to me on the whole, just a few tweaks as noted below.

Thanks for reviewing the PR. I have submitted the requested changes. Makes sense to me!

2021-03-30 08:54 UTC, erikjohnston commented
@f35f0ef9d0e827dae86552d3899f78fc Hi, I'm afraid we need you to sign off on the PR with a real name before we can accept the patch.

2021-04-09 10:59 UTC, anoadragon453 commented
Hey @f35f0ef9d0e827dae86552d3899f78fc, I'm afraid we can't accept this PR without a valid sign-off.

Feel free to re-open with one though!

2021-04-09 10:59 UTC, closed without merging