Remove usage of deprecated attrs cmp argument
matrix-org/synapse pull request #9892
Opened 2021-04-27 11:26 UTC by ulope

The `cmp` argument to the `attr.s` decorator [is deprecated](https://www.attrs.org/en/stable/api.html#attr.s).
This replaces it with `eq` and `order` as suggested in the attrs docs.

Fixes: #9641
Signed-off-by: Ulrich Petri <github@ulo.pe>

### Pull Request Checklist

* [x] Pull request is based on the develop branch
* [ ] Pull request includes a [changelog file](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#changelog). The entry should:
  - Be a short description of your change which makes sense to users. "Fixed a bug that prevented receiving messages from other servers." instead of "Moved X method from `EventStore` to `EventWorkerStore`.".
  - Use markdown where necessary, mostly for `code blocks`.
  - End with either a period (.) or an exclamation mark (!).
  - Start with a capital letter.
* [x] Pull request includes a [sign off](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#sign-off)
* [x] Code style is correct (run the [linters](https://github.com/matrix-org/synapse/blob/master/CONTRIBUTING.md#code-style))

2021-04-27 11:59 UTC, anoadragon453 commented
Looks like the version of `attrs` that we currently support back to (`attrs==19.1.0`) is too old to understand `eq`.

Flipping through the documentation, it looks like `eq` and `order` were added in 19.2.0. Do we have any objection to bumping `attrs` to 19.2.0 (or even 19.3.0) to support this?

@ulope Feel free to bump the version of `attrs` to check that it fixes CI:

https://github.com/matrix-org/synapse/blob/ad8690a26c891a8e3444a3e80bdcdb3ba0d6a02b/synapse/python_dependencies.py#L81

2021-04-27 12:04 UTC, ulope commented
There's a comment above the attrs require:
```
    # we use attr.validators.deep_iterable, which arrived in 19.1.0 (Note:
    # Fedora 31 only has 19.1, so if we want to upgrade we should wait until 33
    # is out in November.)
```

From the commit timestamp I assume this is talking about November 2020. 
So this means it should be fine to update?

2021-04-27 12:18 UTC, anoadragon453 commented
Indeed that sounds promising @ulope. Let me just double-check with our distro packagers that bumping the dependency would be alright :slightly_smiling_face:

2021-04-28 10:03 UTC, anoadragon453 commented
Looks like downstream packages should work with attrs 19.3.0! So feel free to update attrs to that in your PR to fix CI.

Thanks for your patience!

2021-04-28 10:29 UTC, anoadragon453 requested changes
To upgrade attrs.

2021-05-06 13:52 UTC, richvdh commented
Worth noting that attr.s 21.1 *un*deprecates `cmp`, but this is probably still worthwhile

2021-08-17 15:19 UTC, richvdh commented
looks like this is starting to bitrot, so I'm going to close it.

2021-08-17 15:19 UTC, closed without merging